NAME = mdkonline
VERSION:=3.10.3

MDKUPDATE = mdkupdate
MDKAPPLET = mdkapplet
SUBDIRS = po polkit

PREFIX = /
DATADIR = $(PREFIX)/usr/share
ICONSDIR = $(DATADIR)/icons
PIXDIR = $(DATADIR)/$(NAME)
LIBEXECDIR = $(PREFIX)/usr/libexec
BINDIR = $(PREFIX)/usr/bin
FBLIBDIR = $(PREFIX)/usr/lib/libDrakX/drakfirsttime
SYSCONFDIR = $(PREFIX)/etc/sysconfig
SBINREL = ../sbin

localedir = $(PREFIX)/usr/share/locale

override CFLAGS += -DPACKAGE=\"$(NAME)\" -DLOCALEDIR=\"$(localedir)\"

all:
	(find -name .svn -prune -name '*.pm' -o -name mdkapplet\* -o -name mdkupdate -o -name mdvonline_agent.pl -type f) | xargs perl -pi -e 's/\s*use\s+(diagnostics|vars|strict).*//g'
	for d in $(SUBDIRS); do ( make -C $$d $@ ) ; done

clean:
	$(MAKE) -C po $@
	rm -f core .#*[0-9]
	for d in $(SUBDIRS); do ( make -C $$d $@ ) ; done
	find . -name '*~' | xargs rm -f

install: all
	install -d $(PREFIX)/usr/{bin,libexec,share/{mime/packages,$(NAME)/pixmaps,autostart,gnome/autostart,icons/{mini,large}},lib/libDrakX/drakfirsttime}

	install -d $(PREFIX)/usr/{sbin,bin,share/{mime/packages,$(NAME)/pixmaps,autostart,gnome/autostart,icons/{mini,large}},lib/libDrakX/drakfirsttime}
	install -m755 $(MDKUPDATE) $(MDKAPPLET)-config $(MDKAPPLET)-upgrade-helper $(LIBEXECDIR)
	install -m755 $(MDKAPPLET) $(MDKAPPLET)-update-checker $(BINDIR)
	install -d $(SYSCONFDIR)
	install -m644 mdkapplet.conf $(SYSCONFDIR)/mdkapplet
	install -m644 icons/$(NAME)16.png $(ICONSDIR)/mini/$(NAME).png
	install -m644 icons/$(NAME)32.png $(ICONSDIR)/$(NAME).png
	install -m644 icons/$(NAME)48.png $(ICONSDIR)/large/$(NAME).png
	install -m644 pixmaps/*.png $(PIXDIR)/pixmaps
	perl -pi -e "s/version = 1/version = '$(VERSION)'/" mdkonline.pm
	install -m644 mdkonline.pm $(FBLIBDIR)
	install -m644 mdkapplet.pm $(FBLIBDIR)
	install -m644 mdkapplet_gui.pm $(FBLIBDIR)
	install -m644 mdkapplet_urpm.pm $(FBLIBDIR)
	for d in $(SUBDIRS); do make -C $$d $@; done
# mime
	install -m644 mdkonline.xml $(DATADIR)/mime/packages/mdkonline.xml
	mkdir -p $(DATADIR)/mimelnk/application/
	install -m644 x-mdv-exec.desktop $(DATADIR)/mimelnk/application/

cleandist:
	rm -rf $(NAME)-$(VERSION) ../$(NAME)-$(VERSION).tar.bz2


dis: dist
dist:
	@make cleandist
	rm -rf ../$(NAME)-$(VERSION).tar*
	@if [ -e ".svn" ]; then \
		$(MAKE) dist-svn; \
	elif [ -e ".git" ]; then \
		$(MAKE) dist-git; \
	else \
		echo "Unknown SCM (not SVN nor GIT)";\
		exit 1; \
	fi;
	$(info $(NAME)-$(VERSION).tar.xz is ready)

dist-svn:
	rm -rf $(NAME)-$(VERSION)
	svn export -q -rBASE . $(NAME)-$(VERSION)
	tar cfa ../$(NAME)-$(VERSION).tar.xz $(NAME)-$(VERSION)
	rm -rf $(NAME)-$(VERSION)


dist-git:
	 @git archive --prefix=$(NAME)-$(VERSION)/ HEAD | xz -v > $(NAME)-$(VERSION).tar.xz;

log:changelog

changelog: ../common/username
#svn2cl is available in our contrib.
	svn2cl --authors ../common/username.xml --accum
	rm -f ChangeLog.bak
	svn commit -m "Generated by svn2cl the `date '+%c'`" ChangeLog
